name: uplanit_supplier
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^1.0.0
  confetti: ^0.5.4+1
  reactive_forms: ^7.4.0 
  dotted_border: ^1.0.6
  dotted_line: ^2.0.2
  flutter_calendar_carousel: ^1.5.1
  # uplanit_calendar: ^0.0.1+29

  firebase_core: "^0.5.0+1"
  firebase_auth: "^0.18.1+2"
  google_sign_in: "^4.5.1"
  flutter_facebook_login: ^1.1.1

  get_it: ^5.0.1
  google_fonts: ^1.1.0
  google_maps_webservice: ^0.0.16
  html_editor: ^1.0.1
  http: ^0.12.2
  image_picker: ^0.6.7+12
  intl: ^0.16.1
  mime_type: ^0.3.2

  path: ^1.7.0 
  shared_preferences: ^0.5.12+2
  cached_network_image: ^2.3.3
  flutter_inappwebview: ^4.0.0+4
  overlay: ^0.0.1
  provider: ^4.3.2+2
  uuid: ^2.2.2
  fluttertoast: ^7.1.4
  font_awesome_flutter: ^8.10.0
  tabbar: ^0.1.1

  google_maps_flutter: ^0.5.13
  geocoding: ^1.0.5
  google_place: ^0.3.3
  search_map_place: ^0.3.0
  geolocator: ^6.1.5
  location: ^3.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
