enum DrawerPages {
  OVERVIEW,
  BUSINESS_PROFILE,
  BUSINESS_PORTFOLIO,
  MESSAGES,
  SERVICE,
  STORE,
  PAYMENT_PLAN,
  BOOKINGS,
  BUSINESS_CALENDAR,
  TEAM,
  PAYMENT_PROVIDER,
  BUSINESS_INFO,
  SETTINGS
}